### PR TITLE
A) Code reorganization/preparation.

### PR DESCRIPTION
**Pull request by yo1dog**
This pull request  does not change any functionality. It cleans up the code base in preparation for incoming pull requests. Specifically, config file support.

- Code that is or will be called from multiple locations has been abstracted into functions.
- Some code is organized into separate files as main.c was growing quite large.
- Global state was removed (and function interfaces updated accordingly).
- Some complex function interfaces were simplified using structs.
- De-linted to conform with established coding style.

This one is still pretty big, but the rest should be much lighter.

### CODE REVIEW

**Comment by 9ary** [comment]
Hey @yo1dog!

Sorry I never really got around to looking at your changes. I've only glanced at them so far but I'm not sure I want to merge them as they are. I've actually been working on iplboot for the past week and released r9 today.

I've drafted a wish list for r10 in #40. Some of the features that you've implemented are on there. Feel free to comment there if you feel like I've missed something, or have any ideas on how some of those things should work.

I don't think I'm going to accept code contributions until after all of this is done.

**Comment by yo1dog** [comment]
Hey @9ary 

Been a long time for me as well! I will rebase all these onto master. If for no other reason than so I can keep my fork up to date.

Happy to discuss wherever is most appropriate. If you have any high-level thoughts let me know or we can wait until after I rebase so we can talk specific code changes.

- https://github.com/redolution/gekkoboot/pull/28
- https://github.com/redolution/gekkoboot/pull/29
- https://github.com/redolution/gekkoboot/pull/30
- https://github.com/redolution/gekkoboot/pull/31
- https://github.com/redolution/gekkoboot/pull/32
- https://github.com/redolution/gekkoboot/pull/33
- https://github.com/redolution/gekkoboot/pull/34
- https://github.com/redolution/gekkoboot/pull/35

**Comment by 9ary** [comment]
Welcome back! Feel free to rebase and resubmit, as you can see in #40 a lot of this is planned so I'll gladly take the help.

I'd like to do a bit of housekeeping like formatting the code, but that shouldn't prevent you from working in the meantime.

**Comment by yo1dog** [comment]
Reformatting beforehand helps reduce merge conflicts later. Do you have a prettier or auto formatter config you use?


________________________________

**Pull request closed without merging**
